language: php

php:
  - 7.0
  - 7.1
  - hhvm

env:
  - PHP_BIN=php
  - PHP_BIN=php-cgi

matrix:
  allow_failures:
    - php: hhvm

  exclude:
    - php: hhvm
      env: PHP_BIN=php-cgi

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then cat tests/php.ini-unix >> /etc/hhvm/php.ini; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-add tests/php.ini-unix; fi

install:
  - composer self-update
  - composer install --no-interaction --optimize-autoloader

before_script:
  - ./vendor/bin/parallel-lint -e php,phpt --exclude vendor .
  - ./vendor/bin/phpstan analyze --no-progress -l 5 -c ./phpstan.neon ./

script:
  - ./vendor/bin/tester -s -p $PHP_BIN -j 32 -c ./tests/php.ini-unix ./tests/CronnerTests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
